name: qrcodegenerator
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: "flutter"

  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  path_provider: ^2.0.15
  sizer: ^3.0.5
  uuid: ^4.5.1
  msix: ^3.14.2
  flutter_launcher_icons: ^0.14.3
  # image_gallery_saver: ^2.0.3
  flutter_image_gallery_saver: ^0.0.2
  permission_handler: ^12.0.0+1
  google_mobile_ads: ^6.0.0

msix_config:
  display_name: Text QRcode Generator
  publisher_display_name: Dolapo Araoye
  identity_name: 0404Software.Flutterapp
  msix_version: 1.0.0.0
  logo_path: C:\Users\dolapo\Documents\Work\flutterprojects\qr_generator\qrcodegenerator\assets\logo\logo_qrcode_gen.png
  pulbisher:
  store: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_qrcode_gen.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo/logo_qrcode_gen.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo_qrcode_gen.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo_qrcode_gen.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo_qrcode_gen.png
  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/fonts/Kastelov - Axiforma Black.otf
        - asset: assets/fonts/Kastelov - Axiforma Bold.otf
        - asset: assets/fonts/Kastelov - Axiforma Book.otf
        - asset: assets/fonts/Kastelov - Axiforma ExtraBold.otf
        - asset: assets/fonts/Kastelov - Axiforma Heavy.otf
        - asset: assets/fonts/Kastelov - Axiforma Medium.otf
        - asset: assets/fonts/Kastelov - Axiforma Regular.otf
        - asset: assets/fonts/Kastelov - Axiforma SemiBold.otf
        - asset: assets/fonts/Kastelov - Axiforma Thin.otf
